platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  # Kotlin Multiplatform shared module
  pod 'ComposeApp', :path => '../composeApp'

  # Firebase
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  # Google Sign-In
  pod 'GoogleSignIn', '~> 7.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
